- README-ZH.md
- README.md
- cli/pom.xml
- codegen/pom.xml
- codegen/src/main/java/org/apache/servicecomb/toolkit/codegen/ServiceCombCodegen.java
- common/pom.xml
- core/pom.xml
- docgen/pom.xml
- pom.xml
- toolkit-maven-plugin/pom.xml
- toolkit-maven-plugin/src/test/projects/project-generateContracts/pom.xml
- toolkit-maven-plugin/src/test/projects/project-generateContractsDoc/pom.xml
> [SCB-1330] Update the groupid of toolkit

- .travis.yml
- cli/pom.xml
- codegen/pom.xml
- common/pom.xml
- integration-tests/coverage-aggregate/pom.xml
- integration-tests/pom.xml
- pom.xml
- scripts/test.sh
- toolkit-maven-plugin/pom.xml
> [SCB-1334] Enable the Travis CI of the servicecomb-toolkit

- scripts/test.sh
> SCB-1334 add coveralls report generation in CI

- README-ZH.md
- README.md
- cli/src/main/java/org/apache/servicecomb/toolkit/cli/DocGenerate.java
- codegen/src/main/java/org/apache/servicecomb/toolkit/codegen/DefaultCodeGenerator.java
- codegen/src/main/java/org/apache/servicecomb/toolkit/codegen/ServiceCombCodegen.java
- codegen/src/test/java/org/apache/servicecomb/toolkit/codegen/GeneratorTest.java
- common/src/main/java/org/apache/servicecomb/toolkit/common/FileUtils.java
- common/src/main/java/org/apache/servicecomb/toolkit/common/MyersAlgorithm.java
- common/src/test/java/org/apache/servicecomb/toolkit/common/FileUtilsTest.java
- common/src/test/java/org/apache/servicecomb/toolkit/common/TextCompareTest.java
- contractgen/src/main/java/org/apache/servicecomb/toolkit/contractgen/DefaultContractsGenerator.java
- contractgen/src/test/java/org/apache/servicecomb/toolkit/contractgen/DefaultContractsGeneratorTest.java
- core/src/main/java/org/apache/servicecomb/toolkit/Generator.java
- docgen/src/main/java/org/apache/servicecomb/toolkit/docgen/ContractsSwaggerUIGenerator.java
- toolkit-maven-plugin/pom.xml
- toolkit-maven-plugin/src/main/java/org/apache/servicecomb/toolkit/plugin/GenerateMojo.java
- toolkit-maven-plugin/src/main/java/org/apache/servicecomb/toolkit/plugin/GenerateUtil.java
- toolkit-maven-plugin/src/main/java/org/apache/servicecomb/toolkit/plugin/ServiceConfig.java
- toolkit-maven-plugin/src/main/java/org/apache/servicecomb/toolkit/plugin/VerifyMojo.java
- toolkit-maven-plugin/src/test/java/org/apache/servicecomb/toolkit/plugin/GenerateMojoTest.java
- toolkit-maven-plugin/src/test/java/org/apache/servicecomb/toolkit/plugin/GenerateUtilTest.java
> SCB-1383 support toolkit maven plugin commands that generating code

- common/src/main/java/org/apache/servicecomb/toolkit/common/ClassMaker.java
- common/src/test/java/org/apache/servicecomb/toolkit/common/ClassMakerTest.java
- common/src/test/resources/projects/demo-with-correct-pom/pom.xml
- common/src/test/resources/projects/demo-with-invaild-pom/pom.xml
print the error of the command execution and add the unit test for the ClassMaker
> SCB-1422 optimize classmaker

- codegen/src/main/java/org/apache/servicecomb/toolkit/codegen/GeneratorExternalConfigConstant.java
- codegen/src/main/java/org/apache/servicecomb/toolkit/codegen/ServiceCombCodegen.java
- codegen/src/test/java/org/apache/servicecomb/toolkit/codegen/GeneratorTest.java
- contractgen/src/main/java/org/apache/servicecomb/toolkit/contractgen/DefaultContractsGenerator.java
- toolkit-maven-plugin/src/main/java/org/apache/servicecomb/toolkit/plugin/GenerateMojo.java
- toolkit-maven-plugin/src/main/java/org/apache/servicecomb/toolkit/plugin/GenerateUtil.java
- toolkit-maven-plugin/src/main/java/org/apache/servicecomb/toolkit/plugin/MavenPluginUtil.java
- toolkit-maven-plugin/src/test/java/org/apache/servicecomb/toolkit/plugin/GenerateMojoTest.java
- toolkit-maven-plugin/src/test/java/org/apache/servicecomb/toolkit/plugin/GenerateUtilTest.java
- toolkit-maven-plugin/src/test/java/org/apache/servicecomb/toolkit/plugin/InvokeStaticMethodTest.java
- toolkit-maven-plugin/src/test/java/org/apache/servicecomb/toolkit/plugin/MavenPluginUtilTest.java
Support for configuring the toolkit maven plugin in the parent pom and generated microservice project support name configurable
> Support for configuring the toolkit maven plugin in the parent pom

- scripts/test.sh
- toolkit-maven-plugin/src/main/java/org/apache/servicecomb/toolkit/plugin/GenerateUtil.java
- toolkit-maven-plugin/src/test/java/org/apache/servicecomb/toolkit/plugin/GenerateMojoTest.java
- toolkit-maven-plugin/src/test/java/org/apache/servicecomb/toolkit/plugin/GenerateUtilTest.java
- toolkit-maven-plugin/src/test/java/org/apache/servicecomb/toolkit/plugin/InvokeStaticMethodTest.java
- toolkit-maven-plugin/src/test/java/org/apache/servicecomb/toolkit/plugin/TestResourcesEx.java
- toolkit-maven-plugin/src/test/java/org/apache/servicecomb/toolkit/plugin/VerifyMojoTest.java
- toolkit-maven-plugin/src/test/projects/demo-with-contract/pom.xml
- toolkit-maven-plugin/src/test/projects/demo-without-contract/pom.xml
> SCB-1428 Improve toolkit-maven-plugin test to make it running is not dependent by maven plugin

- codegen/src/test/java/org/apache/servicecomb/toolkit/codegen/GeneratorTest.java
remove the unit test for constant
> SCB-1433 remove the unit test for constant

- codegen/src/main/resources/ServiceComb/consumer/apiConsumer.mustache
- codegen/src/main/resources/ServiceComb/libraries/JAX-RS/api.mustache
- codegen/src/main/resources/ServiceComb/libraries/POJO/api.mustache
- codegen/src/main/resources/ServiceComb/libraries/SpringBoot/api.mustache
- codegen/src/main/resources/ServiceComb/libraries/SpringMVC/api.mustache
- codegen/src/test/java/org/apache/servicecomb/toolkit/codegen/TemplateTest.java
- codegen/src/test/resources/no-model.yaml
- codegen/src/test/resources/with-model.yaml
Model is not generated, but the related package is imported
> SCB-1436 Model is not generated, but the related package is imported

- codegen/src/main/java/org/apache/servicecomb/toolkit/codegen/DefaultCodeGenerator.java
- codegen/src/main/java/org/apache/servicecomb/toolkit/codegen/GeneratorExternalConfigConstant.java
- codegen/src/main/java/org/apache/servicecomb/toolkit/codegen/GetRelativeBasePathLambda.java
- codegen/src/main/java/org/apache/servicecomb/toolkit/codegen/MultiContractGenerator.java
- codegen/src/main/java/org/apache/servicecomb/toolkit/codegen/ServiceCombCodegen.java
- codegen/src/main/resources/ServiceComb/consumer/apiConsumer.mustache
- codegen/src/main/resources/ServiceComb/consumer/pom.mustache
- codegen/src/main/resources/ServiceComb/libraries/JAX-RS/api.mustache
- codegen/src/main/resources/ServiceComb/libraries/JAX-RS/pom.mustache
- codegen/src/main/resources/ServiceComb/libraries/POJO/pom.mustache
- codegen/src/main/resources/ServiceComb/libraries/SpringBoot/api.mustache
- codegen/src/main/resources/ServiceComb/libraries/SpringBoot/pom.mustache
- codegen/src/main/resources/ServiceComb/libraries/SpringMVC/api.mustache
- codegen/src/main/resources/ServiceComb/libraries/SpringMVC/pom.mustache
- codegen/src/main/resources/ServiceComb/model/pom.mustache
- codegen/src/main/resources/ServiceComb/project/pom.mustache
- codegen/src/test/java/org/apache/servicecomb/toolkit/codegen/GeneratorTest.java
- common/src/main/java/org/apache/servicecomb/toolkit/common/FileUtils.java
- toolkit-maven-plugin/src/main/java/org/apache/servicecomb/toolkit/plugin/GenerateMojo.java
- toolkit-maven-plugin/src/main/java/org/apache/servicecomb/toolkit/plugin/GenerateUtil.java
- toolkit-maven-plugin/src/test/java/org/apache/servicecomb/toolkit/plugin/GenerateMojoTest.java
> SCB-1444 support to generate mutiple modules in the same project

- codegen/src/main/java/org/apache/servicecomb/toolkit/codegen/ServiceCombCodegen.java
The modules tag is not generated in the pom file when using cli
> SCB-1454 The modules tag is not generated in the pom file when using cli

- toolkit-maven-plugin/src/main/java/org/apache/servicecomb/toolkit/plugin/GenerateMojo.java
- toolkit-maven-plugin/src/main/java/org/apache/servicecomb/toolkit/plugin/GenerateUtil.java
- toolkit-maven-plugin/src/test/java/org/apache/servicecomb/toolkit/plugin/GenerateMojoTest.java
- toolkit-maven-plugin/src/test/java/org/apache/servicecomb/toolkit/plugin/TestResourcesEx.java
- toolkit-maven-plugin/src/test/projects/demo-multi-module/first-module/pom.xml
- toolkit-maven-plugin/src/test/projects/demo-multi-module/pom.xml
Adjust the directory where the document is generated
> SCB-1455 Adjust the directory where the document is generated

- pom.xml
Add information about the release
> SCB-1459 Add information about the release

- integration-tests/pom.xml
- samples/pom.xml
Skip the deployment of samples and it
> SCB-1460 Skip the deployment of samples and it

- README-ZH.md
- README.md
- pom.xml
- samples/README-ZH.md
- samples/README.md
- samples/generate-from-code-sample/README-ZH.md
- samples/generate-from-code-sample/README.md
- samples/generate-from-contract-sample/README-ZH.md
- samples/generate-from-contract-sample/README.md
- samples/verify-with-code-sample/README-ZH.md
- samples/verify-with-code-sample/README.md
> SCB-1463 optimize samples readme

- contractgen/src/main/java/org/apache/servicecomb/toolkit/contractgen/DefaultContractsGenerator.java
- contractgen/src/test/java/org/apache/servicecomb/toolkit/contractgen/DefaultContractsGeneratorTest.java
add support for general jax-rs
> SCB-1487 add support for general jax-rs

- scripts/test.sh
Fix the sonar is not enabled problem
> SCB-1591 sonarcloud.io integration fix

- oas-generator/oas-generator-core/src/main/java/org/apache/servicecomb/toolkit/generator/HttpStatuses.java
- oas-generator/oas-generator-core/src/main/java/org/apache/servicecomb/toolkit/generator/context/OasContext.java
- oas-generator/oas-generator-core/src/main/java/org/apache/servicecomb/toolkit/generator/context/OperationContext.java
- oas-generator/oas-generator-core/src/main/java/org/apache/servicecomb/toolkit/generator/parser/api/OpenApiAnnotationParser.java
translate  comments of oas-generator
> [SCB-1619] translate  comments of oas-generator

- oas-generator/pom.xml
Reduce redundant configuration
> [SCB-1620] optimize the configuration of the oas-generator

- oas-validator/oas-validator-compatibility/src/main/java/org/apache/servicecomb/toolkit/oasv/compatibility/validators/parameter/ParameterAllowEmptyValueChangeDiffValidator.java
- oas-validator/oas-validator-compatibility/src/main/java/org/apache/servicecomb/toolkit/oasv/compatibility/validators/parameter/ParameterAllowReservedChangeDiffValidator.java
- oas-validator/oas-validator-compatibility/src/main/java/org/apache/servicecomb/toolkit/oasv/compatibility/validators/parameter/ParameterRequiredChangeDiffValidator.java
- oas-validator/oas-validator-compatibility/src/main/java/org/apache/servicecomb/toolkit/oasv/compatibility/validators/requestbody/RequestBodyRequiredChangeDiffValidator.java
- oas-validator/oas-validator-style/src/main/java/org/apache/servicecomb/toolkit/oasv/style/validator/openapi/OpenApiTagsSizeGteValidator.java
- oas-validator/oas-validator-style/src/main/java/org/apache/servicecomb/toolkit/oasv/style/validator/openapi/OpenApiVersionGteValidator.java
- toolkit-distribution/pom.xml
- toolkit-distribution/src/assembly/bin.xml
add binary packaging configuration and optimize javadoc
> [SCB-1640] add binary packaging configuration

- cli/src/test/java/org/apache/servicecomb/toolkit/cli/CliTest.java
- common/src/main/java/org/apache/servicecomb/toolkit/common/ClassMaker.java
two problems:
1. get directory size return zero in windows
2. execute mvn command fails in windows
> [SCB-1657] fix test error on windows

- .travis.yml
- README-ZH.md
- README.md
- cli/scripts/cli.cmd
- cli/scripts/cli.sh
- cli/src/main/java/org/apache/servicecomb/toolkit/cli/DocGenerate.java
- cli/src/main/java/org/apache/servicecomb/toolkit/cli/ToolkitMain.java
- docgen/src/main/java/org/apache/servicecomb/toolkit/docgen/ContractsSwaggerUIGenerator.java
- scripts/cliTest.sh
- toolkit-distribution/src/assembly/bin.xml
I wrote two scripts for the cli module
One is a shell script for Linux and the other is a batch script for windows
At the same time, I updated the documentation
But I don't know if these scripts are named properly and if it runs successfully on your machine
Please help to check
> [SCB-1663] add scripts

- toolkit-distribution/pom.xml
- toolkit-distribution/src/release/LICENSE
JIRA: https://issues.apache.org/jira/browse/SCB-1702
> SCB-1702 Exclude oas-validator-test from binary distribution
